[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run start:dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@nestjs/core", 
    "@nestjs/common", 
    "@nestjs/platform-express", 
    "@prisma/client", 
    "express", 
    "serverless-http"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
