services:
  - type: web
    name: whatsapp-chatbot
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 3002
      - key: FRONTEND_URL
        value: https://chatbot-dashboard-rst-argentinas-projects.vercel.app
    autoDeploy: true
